### PR TITLE
Unpin MPICH

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Related https://github.com/conda-forge/mpich-feedstock/issues/56

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
It still used MPICH 3.4, not 3.4.1. Wait another 30 mins or so for the metadata to reflect the update.

**Comment by leofang** [comment]
@conda-forge-admin, please rerun CI

**Comment by leofang** [comment]
@conda-forge-admin, please restart CI

**Comment by leofang** [comment]
Let's wait for another hour or so...

**Comment by leofang** [comment]
@conda-forge-admin, please restart CI

**Comment by awvwgk** [comment]
@conda-forge-admin, please restart CI

**Review by jhrmnn — APPROVED** [review]

**Pull request merged**
