### PR TITLE
Update version to 0.10.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jhrmnn** [comment]
The macOS builds are crashing on missing Accelerate framework. Something probably changed in the build environment since the last version?

**Comment by jhrmnn** [comment]
Weird. It says

```
Found BLAS: /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Accelerate.framework 
```

but then tries to use a different version:

```
ninja: error: '/Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Accelerate.framework', needed by 'src/libmbd.dylib', missing and no known rule to make it
```

**Comment by jhrmnn** [comment]
Actually, it should be linking against the Conda BLAS, not Accelerate...

**Comment by awvwgk** [comment]
Have to check in detail later, but it seems to fail only on MPI builds.There don't seem to be major changes in libmbd's CMake setup.
Maybe I have to give CMake some additional hints on BLAS/LAPACK/ScaLAPACK here or pin an older version of CMake for the build.

@jhrmnn In case you have access to an OSX development environment other than this CI, any help is appreciated.

**Comment by awvwgk** [comment]
Looks like ScaLAPACK was not picked up correctly. Fixed this by adding `-DSCALAPACK_LIBRARIES=scalapack` to the build script.

**Pull request merged**
